initial database design
snowhirata/chat-space pull request #1
Opened 2019-03-04 01:48 UTC by snowhirata

#WHAT
データベースの設計

#WHY
データ操作のため

2019-03-04 09:03 UTC, ghost requested changes

2019-03-04 09:03 UTC, hiroki5123 commented on README.md
> +| user_id    | integer     | null: false, foreign_key: true |
必要ありません

2019-03-04 09:03 UTC, hiroki5123 commented on README.md
> +- has_many   :messages
アソシエーションが１つ足りないので、見直してみましょう

2019-03-04 09:03 UTC, hiroki5123 commented on README.md
> +| group_name | string      | null: false                    |
nameでいいと思います。

2019-03-04 09:03 UTC, hiroki5123 commented on README.md
> +| group_id   | integer     | null: false, foreign_key: true |
必要ありません。

2019-03-04 09:03 UTC, hiroki5123 commented on README.md
> +- has_many   :messages
アソシエーションが１つ足りないので見直してみましょう

2019-03-04 09:03 UTC, hiroki5123 commented on README.md
> +| message_id | integer     | null: false, foreign_key: true |
必要ありません

2019-03-04 09:03 UTC, hiroki5123 commented on README.md
> +| body       | text        | null: false, foreign_key: true |
NOT NULL制約外しましょう

2019-03-04 10:17 UTC, snowhirata commented on README.md
> +| user_id    | integer     | null: false, foreign_key: true |
修正しました。

2019-03-04 10:18 UTC, snowhirata commented on README.md
> +| group_id   | integer     | null: false, foreign_key: true |
修正しました。

2019-03-04 10:18 UTC, snowhirata commented on README.md
> +| message_id | integer     | null: false, foreign_key: true |
修正しました。

2019-03-04 11:46 UTC, snowhirata commented on README.md
> +- has_many   :messages
修正しました。

2019-03-04 11:46 UTC, snowhirata commented on README.md
> +- has_many   :messages
修正しました。

2019-03-04 12:15 UTC, ghost requested changes

2019-03-04 12:15 UTC, hiroki5123 commented on README.md
> +- has_many   :groups, through: :menbers
membersですね

2019-03-04 12:15 UTC, hiroki5123 commented on README.md
> +| group_name | string      | null: false                    |
こちら修正しましょう

2019-03-04 12:15 UTC, hiroki5123 commented on README.md
> +- has_many   :users, through: :menbers
membersです

2019-03-04 12:15 UTC, hiroki5123 commented on README.md
> +| body       | text        | null: false, foreign_key: true |
こちら修正しましょう

2019-03-04 12:16 UTC, snowhirata commented on README.md
> +| group_name | string      | null: false                    |
修正しました。

2019-03-04 12:17 UTC, snowhirata commented on README.md
> +| body       | text        | null: false, foreign_key: true |
修正しました。

2019-03-04 12:21 UTC, snowhirata commented on README.md
> +- has_many   :groups, through: :menbers
修正しました。

2019-03-04 12:21 UTC, snowhirata commented on README.md
> +- has_many   :users, through: :menbers
修正しました。

2019-03-04 12:34 UTC, ghost requested changes

2019-03-04 12:34 UTC, hiroki5123 commented on README.md
> +- has_many   :groups, through: :menbers
menbersのままになってます

2019-03-05 00:35 UTC, snowhirata commented
members修正しました。

2019-03-05 02:07 UTC, miyagit reviewed
belongs_toのあとは複数形にしないようにしましょう。

2019-03-05 10:10 UTC, snowhirata commented
単数形に修正しました。

2019-03-05 10:14 UTC, TOMARUMARU commented on README.md
> +| name       | string      | null: false                    |
indexとuniqueを加えましょう

2019-03-05 10:14 UTC, TOMARUMARU commented on README.md
> +| image      | string      | foreign_key: true              |
外部キー外しましょう

2019-03-05 10:14 UTC, TOMARUMARU commented on README.md
> +| body       | text        | foreign_key: true              |
外部キー外しましょう

2019-03-05 12:57 UTC, snowhirata commented on README.md
> +| image      | string      | foreign_key: true              |
修正しました。

2019-03-05 12:57 UTC, snowhirata commented on README.md
> +| body       | text        | foreign_key: true              |
修正しました。

2019-03-05 13:13 UTC, snowhirata commented on README.md
> +| name       | string      | null: false                    |
修正しました。

2019-03-06 02:01 UTC, miyagit approved these changes
LGTMです。

2019-03-06 02:09 UTC, hzak2xx approved these changes
LGTM

2019-03-06 02:35 UTC, merged