[WIP]Asynchronous send messages
snowhirata/chat-space pull request #6
Opened 2019-03-12 07:43 UTC by snowhirata

アドバイスが欲しいです。
<したいこと>
メッセージ送信機能の非同期化の実装の中で、animateメソッドを使い自動でメッセージ最下部に移動する機能が実装できません。
<エラー内容>
メッセージ送信しても最下部に移動しない。
<調べたこと>
Animateメソッド前後の要素を.messages、.message、.lower-messageなど変更しましたが、最下部に移動しません。

2019-03-12 07:54 UTC, ghost requested changes
質問がある場合はこちらではなく、TECH::CONNECTでご質問ください。
よろしくお願い致します。

2019-03-12 07:56 UTC, snowhirata commented
こちらでも質問可能と勘違いしておりました。失礼しました。

2019-03-13 02:54 UTC, miyagit commented on app/assets/javascripts/message.js
> +      $('.form__message, .form__mask__image').val('');
form属性のresetメソッドを使いましょう。

2019-03-13 03:16 UTC, snowhirata commented on app/assets/javascripts/message.js
> +      $('.form__message, .form__mask__image').val('');
修正しました。

2019-03-13 03:18 UTC, hzak2xx approved these changes
LGTM

2019-03-13 03:20 UTC, merged